services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    environment:
      - discovery.type=single-node

  app:
    build: .
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - '127.0.0.1:3000:3000'
