name: Publish

on:
  push:
    branches: 
      - '**'
    tags: 
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: docker/login-action@v2
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - uses: rlespinasse/github-slug-action@v4
    - name: Build the project
      run: |
        npm ci
        npm run build
    - name: Build Docker image
      run: docker build --tag ${{ github.repository }}:${{ env.GITHUB_REF_SLUG }} .
    - name: Publish to DockerHub
      run: docker push ${{ github.repository }}:${{ env.GITHUB_REF_SLUG }}