name: Test

on:
  push:
    branches: 
      - '**'

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint    
  test:
    runs-on: ubuntu-latest    
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
        env:
          discovery.type: single-node
        ports:
          - 9200:9200
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci      
      - name: Run Unit Tests
        run: npm run test
      - name: Run End-to-end Test
        run: npm run test:e2e